import streamlit as st
from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables FIRST, before importing modules that use it
env_path = Path(__file__).parent / ".env"
load_dotenv(dotenv_path=env_path)

from ai_engine import generate_multiple_recipes
from youtube import generate_youtube_search_url
from utils.preprocessing import normalize_ingredients

# Page configuration
st.set_page_config(
    page_title="AI Recipe Recommender",
    page_icon="🍽️",
    layout="wide"
)

st.title("🍽️ AI-Powered Recipe Recommender")
st.markdown("Find the perfect recipe based on your ingredients, time, and preferences!")

# Sidebar inputs
with st.sidebar:
    st.header("📋 Your Preferences")
    
    # Ingredients input
    ingredients_text = st.text_area(
        "Enter your available ingredients:",
        placeholder="e.g., tomato, onion, chicken, garlic",
        height=100
    )
    
    # Cooking time slider
    cooking_time = st.slider(
        "Available cooking time (minutes):",
        min_value=5,
        max_value=120,
        value=30,
        step=5
    )
    
    # Meal type dropdown
    meal_types = ["Breakfast", "Lunch", "Dinner", "Snack"]
    meal_type = st.selectbox("Meal type:", meal_types)
    
    # Cuisine dropdown
    cuisines = [
        "Indian", "Italian", "Chinese", "Mexican", 
        "Thai", "Japanese", "Mediterranean", "American"
    ]
    cuisine = st.selectbox("Cuisine preference:", cuisines)
    
    # Search button
    search_button = st.button("🔍 Find Recipes", type="primary", use_container_width=True)

# Main area
if search_button:
    # Validate input
    if not ingredients_text.strip():
        st.error("❌ Please enter at least one ingredient!")
    else:
        with st.spinner("🤖 AI is generating 3 perfect recipes..."):
            try:
                # Normalize ingredients
                user_ingredients = normalize_ingredients(ingredients_text)
                
                # Generate multiple recipes using Gemini AI
                recipes = generate_multiple_recipes(
                    user_ingredients,
                    meal_type,
                    cuisine,
                    cooking_time,
                    num_recipes=3
                )
                
                if recipes is None or len(recipes) == 0:
                    st.error("❌ Could not generate recipes. Please try again!")
                else:
                    # Display results
                    st.success(f"✅ {len(recipes)} Recipes Generated by AI!")
                    
                    # Create tabs for each recipe
                    tabs = st.tabs([f"Recipe {i+1}" for i in range(len(recipes))])
                    
                    for idx, (tab, recipe) in enumerate(zip(tabs, recipes)):
                        with tab:
                            col1, col2 = st.columns([2, 1])
                            
                            with col1:
                                st.header(f"🍲 {recipe['recipe_name']}")
                                
                                # Recipe details
                                detail_col1, detail_col2 = st.columns(2)
                                with detail_col1:
                                    st.metric("⏱️ Cooking Time", f"{recipe['cooking_time']} min")
                                with detail_col2:
                                    st.metric("🍜 Meal Type", recipe['meal_type'])
                                
                                # Ingredients used
                                st.subheader("📦 Ingredients:")
                                ingredients_list = [ing.strip() for ing in recipe['ingredients'].split() if ing.strip()]
                                for ing in ingredients_list:
                                    st.write(f"• {ing}")
                                
                                # Instructions
                                st.subheader("👨‍🍳 Instructions:")
                                st.write(recipe['instructions'])
                                
                                # AI explanation
                                st.subheader("🤖 Why this recipe?")
                                st.info(recipe['reason'])
                            
                            with col2:
                                # YouTube link
                                youtube_url = generate_youtube_search_url(
                                    recipe['recipe_name'],
                                    recipe['cuisine']
                                )
                                st.markdown(
                                    f"<a href='{youtube_url}' target='_blank' style='display: inline-block; "
                                    f"padding: 10px 20px; background-color: #FF0000; color: white; "
                                    f"border-radius: 5px; text-decoration: none; font-weight: bold;'>"
                                    f"▶ Watch on YouTube</a>",
                                    unsafe_allow_html=True
                                )
                                
                                # Additional info
                                st.markdown("---")
                                st.subheader("📊 Recipe Info:")
                                st.write(f"**Cuisine:** {recipe['cuisine']}")
                                st.write(f"**Type:** {recipe['meal_type']}")
                                st.write(f"**Generated by:** Gemini AI ✨")
            
            except Exception as e:
                st.error(f"❌ Error occurred: {str(e)}")
                st.write("Please check your input and try again.")

# Footer
st.markdown("---")
st.markdown(
    "<div style='text-align: center; color: gray;'>"
    "Powered by Google Gemini AI | Built with Streamlit"
    "</div>",
    unsafe_allow_html=True
)
